GO 
CREATE DATABASE QLBANHANG
GO
USE QLBANHANG

GO


CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(50) NOT NULL, 
	CHUCVU NVARCHAR(50), 
	TENTK VARCHAR(50),
	MATKHAU VARCHAR(50), 
	SDT VARCHAR(12),
	DIACHI NVARCHAR(50),
	
)

GO
CREATE TABLE HANG
(
	MAHANG VARCHAR(10) PRIMARY KEY,
	TENHANG NVARCHAR(50) NOT NULL,
	DONGIAHANG BIGINT, 
	NHASX NVARCHAR(50), 
	MOTA NVARCHAR(50)
)

GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) PRIMARY KEY, 
	TENKH NVARCHAR(50),
	DIACHI NVARCHAR(50),
	DIENTHOAI NVARCHAR(12)
)

GO
CREATE TABLE HOADON
(
	MAHD VARCHAR(10) PRIMARY KEY,
	MAKH VARCHAR(10) NOT NULL, 
	NGAYLAP VARCHAR(80)
)

GO
CREATE TABLE CTHD
(
	MAHD VARCHAR(10),
	MAHANG VARCHAR(10),
	SOLUONGMUA INT,
	DONGIABAN BIGINT,
	THANHTIEN BIGINT,
	PRIMARY KEY(MAHD, MAHANG)
)

GO
ALTER TABLE CTHD ADD CONSTRAINT FK_MAHANG FOREIGN KEY (MAHANG) REFERENCES HANG(MAHANG)
ALTER TABLE CTHD ADD CONSTRAINT FK_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE HOADON ADD CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_MAHD_MANV FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

GO
INSERT INTO NHANVIEN VALUES ('NV01', N'PHẠM PHƯƠNG TOÁN', N'QUẢN LÝ', 'admin', 'admin', '01687229666', N'AN MINH, KIÊN GIANG'),
							('NV02', N'ĐÀO THANH HUY', N'THỦ KHO', 'thienhoang97', '12345', '016987654321', N'PHÚ QUỐC, KIÊN GIANG'),
							('NV03', N'NGUYỄN HẢI ÂU', N'NHÂN VIÊN BÁN HÀNG', 'haiau98', 'haiau123', '0987654321', N'VĨNH THUẬN, KIÊN GIANG')

GO
INSERT INTO HANG VALUES ('HH01', N'XÚC XÍCH', 10000, N'BOOM BOOM', N'XÚC XÍCH HEO'),
						('HH02', N'MÌ TÔM', 3000, N'HẢO HẢO', N'MÌ TÔM CHUA CAY'),
						('HH03', N'QUẠT', 125000, 'FUJITSU', N'QUẠT ĐIỆN')
GO
INSERT INTO KHACHHANG VALUES ('KH01', N'DANH THÁI BÌNH', N'CHÂU THÀNH, KIÊN GIANG', '0988988988'),
							('KH02', N'TRẦN TRÂN', N'TÂN HIỆP, KIÊN GIANG', '01234567890'),
							('KH03', N'ĐÀO THỊ DIỄM', N'TÂN HIỆP, KIÊN GIANG', '0977898090')